[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback so deep links work (e.g., /auth, /learning, /test)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
